"""empty message

Revision ID: 006fa42c18d9
Revises: 5c2694e13958
Create Date: 2024-02-24 19:10:50.605144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006fa42c18d9'
down_revision = '5c2694e13958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('accepted_requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dj', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dj_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_dj_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_dj_username'), ['username'], unique=True)

    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.Boolean(), nullable=False),
    sa.Column('DJ_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DJ_id'], ['dj.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_DJ_id'), ['DJ_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_timestamp'))
        batch_op.drop_index(batch_op.f('ix_request_song_id'))
        batch_op.drop_index(batch_op.f('ix_request_DJ_id'))

    op.drop_table('request')
    op.drop_table('user')
    op.drop_table('song')
    with op.batch_alter_table('dj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dj_username'))
        batch_op.drop_index(batch_op.f('ix_dj_phone'))
        batch_op.drop_index(batch_op.f('ix_dj_email'))

    op.drop_table('dj')
    # ### end Alembic commands ###
