"""empty message

Revision ID: 5c2694e13958
Revises: a33d6760c30a
Create Date: 2024-02-24 18:23:54.230672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2694e13958'
down_revision = 'a33d6760c30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_dj_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dj_phone'))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
