"""empty message

Revision ID: bb0b549de322
Revises: 
Create Date: 2024-03-27 12:50:41.409686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0b549de322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('accepted_requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dj'))
    )
    with op.batch_alter_table('dj', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dj_username'), ['username'], unique=False)

    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song'))
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('dj_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dj_id'], ['dj.id'], name=op.f('fk_event_dj_id_dj')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_dj_id'), ['dj_id'], unique=False)

    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('in_stack', sa.Boolean(), nullable=False),
    sa.Column('dj_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dj_id'], ['dj.id'], name=op.f('fk_request_dj_id_dj')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_request_event_id_event')),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_request_song_id_song')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_request_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_dj_id'), ['dj_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_song_id'))
        batch_op.drop_index(batch_op.f('ix_request_event_id'))
        batch_op.drop_index(batch_op.f('ix_request_dj_id'))

    op.drop_table('request')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_dj_id'))

    op.drop_table('event')
    op.drop_table('user')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_name'))

    op.drop_table('song')
    with op.batch_alter_table('dj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dj_username'))

    op.drop_table('dj')
    # ### end Alembic commands ###
